[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/pb/pocketbase serve --http=0.0.0.0:$PORT --dir=/pb/pb_data --publicDir=/pb/pb_public"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[environments.production.variables]
PORT = "8080"
ADMIN_EMAIL = "ddinsmore8@gmail.com"
ADMIN_PASSWORD = "MADcap(123)"
APP_NAME = "Digital Resume Hub"
NODE_ENV = "production"