name: Deploy Full Stack Application

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-backend:
    name: Deploy Backend to Railway
    runs-on: ubuntu-latest
    outputs:
      backend-url: ${{ steps.get-url.outputs.url }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH

      - name: Deploy Backend
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway login --browserless
          railway link 387321dc-13de-40a6-88b7-b6218716fb27
          railway up --detach

      - name: Wait for deployment
        run: sleep 45

      - name: Get Backend URL
        id: get-url
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway login --browserless
          URL=$(railway domain 2>/dev/null || echo "")
          if [ -z "$URL" ]; then
            URL=$(railway status --json | jq -r '.deployments[0].url // empty' 2>/dev/null || echo "")
          fi
          echo "Backend URL: $URL"
          echo "url=$URL" >> $GITHUB_OUTPUT

      - name: Test Backend Health
        run: |
          if [ ! -z "${{ steps.get-url.outputs.url }}" ]; then
            echo "Testing backend health..."
            curl -f "${{ steps.get-url.outputs.url }}/api/health" || echo "Health check failed"
          else
            echo "No backend URL available for testing"
          fi

  deploy-frontend:
    name: Deploy Frontend to Netlify
    runs-on: ubuntu-latest
    needs: deploy-backend
    if: always() && (needs.deploy-backend.result == 'success' || needs.deploy-backend.result == 'skipped')
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install dependencies
        run: |
          cd app
          npm ci

      - name: Build frontend
        env:
          PUBLIC_POCKETBASE_URL: ${{ needs.deploy-backend.outputs.backend-url || secrets.PUBLIC_POCKETBASE_URL || 'https://api.digitalresumehub.com' }}
          PUBLIC_APP_URL: https://digitalresumehub.com
          NODE_ENV: production
        run: |
          cd app
          echo "Building with backend URL: $PUBLIC_POCKETBASE_URL"
          npm run build

      - name: Deploy to Netlify
        if: secrets.NETLIFY_AUTH_TOKEN != ''
        uses: netlify/actions/cli@master
        with:
          args: deploy --prod --dir=app/build
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Output deployment info
        run: |
          echo "🚀 Deployment Summary:"
          echo "Backend: ${{ needs.deploy-backend.outputs.backend-url || 'Not deployed' }}"
          echo "Frontend: https://digitalresumehub.com (if Netlify configured)"